// <auto-generated />
using System;
using CoreRoutes.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreRoutes.Migrations
{
    [DbContext(typeof(RoutesDBContext))]
    partial class RoutesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreRoutes.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CentralAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CoreRoutes.Models.CompanySite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyFK")
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyFK");

                    b.ToTable("CompanySites");
                });

            modelBuilder.Entity("CoreRoutes.Models.DeliveryChecking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeliveryStateFK")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeFK")
                        .HasColumnType("int");

                    b.Property<int>("UserFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryStateFK");

                    b.HasIndex("ServiceTypeFK");

                    b.HasIndex("UserFK");

                    b.ToTable("DeliveryCheckings");
                });

            modelBuilder.Entity("CoreRoutes.Models.DeliveryState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            State = "Available"
                        },
                        new
                        {
                            Id = 2,
                            State = "Selected"
                        },
                        new
                        {
                            Id = 3,
                            State = "Working"
                        },
                        new
                        {
                            Id = 4,
                            State = "Delivered"
                        },
                        new
                        {
                            Id = 5,
                            State = "Skipped"
                        },
                        new
                        {
                            Id = 6,
                            State = "Undelivered"
                        });
                });

            modelBuilder.Entity("CoreRoutes.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserRole")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2021, 2, 27, 14, 52, 45, 656, DateTimeKind.Local).AddTicks(3674),
                            UpdateAt = new DateTime(2021, 2, 27, 14, 52, 45, 657, DateTimeKind.Local).AddTicks(1373),
                            UserRole = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2021, 2, 27, 14, 52, 45, 657, DateTimeKind.Local).AddTicks(1656),
                            UpdateAt = new DateTime(2021, 2, 27, 14, 52, 45, 657, DateTimeKind.Local).AddTicks(1661),
                            UserRole = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2021, 2, 27, 14, 52, 45, 657, DateTimeKind.Local).AddTicks(1662),
                            UpdateAt = new DateTime(2021, 2, 27, 14, 52, 45, 657, DateTimeKind.Local).AddTicks(1663),
                            UserRole = "Driver"
                        });
                });

            modelBuilder.Entity("CoreRoutes.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanySiteFK")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeFK")
                        .HasColumnType("int");

                    b.Property<int>("WeekdayFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanySiteFK");

                    b.HasIndex("ServiceTypeFK");

                    b.HasIndex("WeekdayFK");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("CoreRoutes.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleFK");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("CoreRoutes.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleFK");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2021, 2, 27, 14, 52, 45, 686, DateTimeKind.Local).AddTicks(8376),
                            Email = "eretana60@gmail.com",
                            Password = "$2a$06$NgmQD14PsZpR6NacE10ix.ynDnOQ7oxJNdbOmQRflZGzbgyPfKbO2",
                            RoleFK = 1,
                            UpdateAt = new DateTime(2021, 2, 27, 14, 52, 45, 686, DateTimeKind.Local).AddTicks(8688),
                            Username = "eretana"
                        });
                });

            modelBuilder.Entity("CoreRoutes.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("VehicleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            VehicleName = "Pickup"
                        },
                        new
                        {
                            Id = 2,
                            VehicleName = "Camion Sisterna"
                        },
                        new
                        {
                            Id = 3,
                            VehicleName = "Camion Mundanza"
                        });
                });

            modelBuilder.Entity("CoreRoutes.Models.Weekday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DayName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Weekdays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayName = "Monday"
                        },
                        new
                        {
                            Id = 2,
                            DayName = "Tuesday"
                        },
                        new
                        {
                            Id = 3,
                            DayName = "Wednesday"
                        },
                        new
                        {
                            Id = 4,
                            DayName = "Thursday"
                        },
                        new
                        {
                            Id = 5,
                            DayName = "Friday"
                        },
                        new
                        {
                            Id = 6,
                            DayName = "Saturday"
                        },
                        new
                        {
                            Id = 7,
                            DayName = "Sunday"
                        });
                });

            modelBuilder.Entity("CoreRoutes.Models.CompanySite", b =>
                {
                    b.HasOne("CoreRoutes.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CoreRoutes.Models.DeliveryChecking", b =>
                {
                    b.HasOne("CoreRoutes.Models.DeliveryState", "DeliveryState")
                        .WithMany()
                        .HasForeignKey("DeliveryStateFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreRoutes.Models.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreRoutes.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryState");

                    b.Navigation("ServiceType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreRoutes.Models.Route", b =>
                {
                    b.HasOne("CoreRoutes.Models.CompanySite", "CompanySite")
                        .WithMany()
                        .HasForeignKey("CompanySiteFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreRoutes.Models.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreRoutes.Models.Weekday", "Weekday")
                        .WithMany()
                        .HasForeignKey("WeekdayFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanySite");

                    b.Navigation("ServiceType");

                    b.Navigation("Weekday");
                });

            modelBuilder.Entity("CoreRoutes.Models.ServiceType", b =>
                {
                    b.HasOne("CoreRoutes.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CoreRoutes.Models.User", b =>
                {
                    b.HasOne("CoreRoutes.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
